language: php
php:
  - 5.3

before_script:
 - sudo apt-get update
 - sudo apt-get install php5-cli php5-common
 - /home/travis/.phpenv/versions/5.3.27/bin/composer.phar self-update
 - composer install


script: phpunit
